### ISSUE TITLE
Not able to get a working build after folder/file restructuring

### ISSUE THREAD

**Issue by tfrank64** [IBM-MIL/IBM-Ready-App-for-Healthcare#1]
In the **restructuring branch**, a lot of changes have been made with the folder structure as well as renaming certain files. We have gotten a successful Jenkins build, but still having issues with getting data from MFP.

**Comment by atcabral** [comment]
Is this a blocker for every Ready App repo?

**Comment by kweinmeister** [comment]
Good question @atcabral. @tfrank64, can you include the details of the MFP problem? I think we should also rename the issue to focus more on "getting data from MFP" and less on the build.

**Comment by tfrank64** [comment]
@atcabral It could potentially be a problem for Ready Apps that need to change MFP folder and file names.
@kweinmeister A few more details about the issue is that we can get a successful build, but all the MFP artifacts, such as adapters, are not being deployed correctly. Resulting in the healthcare-mfpf runtime not being available on our development server. We can be for sure this will work for an external user until we get it working on our own system.

**Comment by tfrank64** [comment]
What's left is essentially getting a working release build

**Comment by trishayy** [comment]
Got successful release build on 11/9/2016
