### ISSUE TITLE
User selection magnification tool pops up when holding down on a webview

### ISSUE THREAD

**Issue by tfrank64** [IBM-MIL/IBM-Ready-App-for-Healthcare#10]
See top of screenshot for details

![simulator screen shot oct 21 2015 3 39 32 pm](https://cloud.githubusercontent.com/assets/4023136/10677077/e8f53cb0-78cf-11e5-960b-226f93e48e79.png)

**Comment by Hsaylor** [comment]
Magnification should be disabled as of commit df710fc
