### ISSUE TITLE
Android pain management UI is distorted

### ISSUE THREAD

**Issue by tfrank64** [IBM-MIL/IBM-Ready-App-for-Healthcare#12]
This issue may not be present on all devices, but this happened on a nexus 7 device, but not on an nexus 5 emulator.

![screenshot_2015-10-23-15-03-11](https://cloud.githubusercontent.com/assets/4023136/10704484/c1c9b7f6-799c-11e5-94d3-7a70e909518a.png)

**Comment by Hsaylor** [comment]
Updated dpi to pixel conversion in 96cbc8be3e58c6243a05a1fe13e0f766fceb042c; seems to have fixed the issue.
