### ISSUE TITLE
Crash on completing Pain Management flow on Android 

### ISSUE THREAD

**Issue by tfrank64** [IBM-MIL/IBM-Ready-App-for-Healthcare#13]
This has been reproducible for me by going through the pain management flow, which is the body part picker, pain rating, confirm yes on popup, then tap the confirmation popup. Right after that, the app crashes for me.

Devices failed on: 
* Nexus 5 emulator, android 5.0 x86, API 21
* Nexus 7 tablet, android 5.0.2

**Comment by trishayy** [comment]
Harrison cannot reproduce on a physical device. We believe this only happens on the emulator.
