### ISSUE TITLE
With iOS 9, UIWebViews not behaving correctly

### ISSUE THREAD

**Issue by tfrank64** [IBM-MIL/IBM-Ready-App-for-Healthcare#2]
On the **ios9_updates** branch, the web views in the app are not working correctly. For example, no data is being injected into the graphs. Also, pressing "Get Started" on the dashboard causes the whole view to turn white and seemingly disappear. This is directly related to this [issue](https://github.com/angular/angular.js/issues/12241) on the Angular js repo.

**Comment by jballands** [comment]
3dd76a5, c40fd7c, 2a5cda2
