### ISSUE TITLE
Change bundle name to "RA Healthcare"

### ISSUE THREAD

**Issue by atcabral** [IBM-MIL/IBM-Ready-App-for-Healthcare#3]
The MaaS 360 democenter requires that the democenter title matches the app name.

the bundle name can be found in the info.plist and you can test you changed the right value by running the app and looking at the name under the app icon.

This needs to be done asap and then run (or notify me and I will run) an MQA build with the updated ipa

**Comment by trishayy** [comment]
Fixed with latest commit.
