### ISSUE TITLE
Documentation wrong for Xcode version

### ISSUE THREAD

**Issue by trishayy** [IBM-MIL/IBM-Ready-App-for-Healthcare#6]
In the docs under the developing iOS tab, it states that you need Xcode version 6.1. 
This needs to be updated to version 6.4.

**Comment by tfrank64** [comment]
Update: need to change to Xcode 7
Also, need to specify you must be using 10.10+ Mac because I had to remove a ResourceRules reference as it is deprecated, for more info, click [here](http://stackoverflow.com/a/32653351/2280737).

**Comment by tfrank64** [comment]
This is a all updated now
