### ISSUE TITLE
Detect whether Physio is being installed on iPad and display popup saying iPads are not supported

### ISSUE THREAD

**Issue by atcabral** [IBM-MIL/IBM-Ready-App-for-Healthcare#7]
Because of HealthKit, iPads are not supported in Physio.

**Comment by kweinmeister** [comment]
FYI: http://stackoverflow.com/questions/6447369/how-to-prevent-installation-of-an-application-on-the-ipad

**Comment by tfrank64** [comment]
A system alert now pops up if running on iPad. Alert text: "HealthKit is not supported on iPad. Please download RA Healthcare on an iPhone"
